### ISSUE TITLE
Back sur payements propriétaire.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#100]
Quand tous les payements au propriétaire sont faits, le back du browser ne fonctionne pas (message : il n'y a pas encore de payement locataire à verser au propriétaire).
Si le back était ok, on pourrait aller au tableau des payements sans remonter à "mes biens".

**Comment by krieklambic** [comment]
L'hyperlien au dessus du tableau marche maintenant !
(=> Ne JAMAIS utiliser le bouton back du browser !)
