### ISSUE TITLE
Records to delete.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#102]
Suite à la correction du tableau des payements dans la version passée en production le  28 juin, des montants sont erronés dans ce tableau, à cause d’anciennes données créées précédemment : il faut donc supprimer en production les données relatives aux payements du locataire et aux versements au propriétaire pour :
Record 1 : Le bien GARE 5/001        Proprio = BELLOT        Locataire = CAUWE
Record 2 : Le bien ERGOT 3/503   Proprio = ROMAURENA     Locataire = DRAGAN

**Comment by comexis** [comment]
Pour le premier j'ai delete 7 paiements locataires et 3 versements proprietaires
Pour le second 7 paiements locataires et è versements proprietaires

Dans l'avenir, ce serait bien d'eviter de supprimer comme cela directement dans la base de données... C'est assez risque et une erreur est vite survenue...

Julien
