### ISSUE TITLE
Gestion des copropriétés : mailto.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#104]
A partir de la copropriété (présente dans le détail d’un bien immobilier), qui devient un hyperlien cliquable par l’utilisateur, le système doit retrouver toutes les adresses mails des locataires de cette copropriété et ouvrir une fenêtre de mail avec cette «adress list».
Le système ne contrôlera pas les adresses mails absentes, incorrectes, obsolètes, etc.

**Comment by comexis** [comment]
resolu avec le commit 928f90829dcf38664e477681d9fea3227f18d182

Solution simple : quand une copropriete est presente sur le bien, j'affiche un bouton "Contacter les locataires".
Lorsque l'on click sur le bouton, on rapatrie les emails du serveur et j'affiche un lien envoyer un mails aux locataires

Si pas de mails disponible, un texte est affiche "Pas d'adresse mails disponible"

**Comment by comexis** [comment]
Bizarre ne fonctionne pas en test... Ca doit surement etre une histoire d'index, je check ca demain

**Comment by btytgat** [comment]
Le bouton "Envoyer les emails" a disparu.

**Comment by comexis** [comment]
non il a pas disparu, fred a monter une nouvelle version sans prendre mes changements.... De meme, il a pas committé ses changements dans github, donc moi je ne sais pas reprendre les siens...

**Comment by btytgat** [comment]
Waaaooohhh ...
