### ISSUE TITLE
Statut actif/non actif sur les locataires.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#106]
A implémenter pour fin 2012 (au plus tard) : Ajouter un statut actif/non actif sur les locataires.
La liste des locataires présentera par défaut uniquement les locataires actifs. Attention, cette fonctionnalité n’est pas un delete logique mais un filtre. 
Les locataires non-actifs doivent rester accessibles et/ou modifiables. 

Solution retenue : 
Ajout d’une case à cocher «Actif /Non actif» (nommé plus loin checkbox) dans les différentes entités existantes  :
-   Propriétaires
-   Biens
-   Locataires
-   Locations
-   Payements
-   Dépenses
-   Versements aux propriétaires

Fonctionnement
Ce checkbox ne sera utilisé dans un premier temps que pour les locataires.
L’utilisateur pourra désactiver ou réactiver un locataire manuellement, en le cochant non actif ou actif.

Comment désactiver un locataire
Dans l’écran «Edition d’un locataire », positionner le checkbox non actif (cocher la case).

Visualisation du statut 
Dans les écrans «Liste des locataires» et «Détails d’un locataire», le statut actif ou non actif  sera affiché après le champ «Nom».
Par défaut seuls les locataires actifs sont affichés.

Comment faire réapparaître les locataires désactivés
Pour voir réapparaître, dans la liste des locataires, ceux qui sont en statut non actif, l’utilisateur pourra cliquer sur un nouveau bouton en haut de la liste, à droite du filtre déjà existant.
Ce bouton , non coché par défaut, sera intitulé par exemple «Afficher aussi les Non actifs».
Attention, ces locataires restent désactivés.

Comment réactiver un locataire
Via l’écran «Edition d’un locataire», positionner le checkbox non actif (décocher la case).

**Comment by krieklambic** [comment]
Attention ! La vision ici me parrait un peu simpliste. Désactiver une entité a des conséquences un peu plus importantes que d'afficher un checkbox...

Par exemple, pour les locataires:

lorsqu'on désactive un locataire celui ci ne devrait plus non plus apparaitre dans la dropdown "locataire" de l'ecran "Creation d'une location". 

De meme, peut on désactiver un locataire lorsqu'il est encore référencé dans une location existante/en cours ou future ? 

Je pense qu'une analyse un peu plus poussée est nécessaire, sans quoi le datastore n'aura plus aucune intégrité et l'application va devenir totalement incohérente.

**Comment by comexis** [comment]
Effectivement je suis d'accord avec Fred, faut une analyse plus approfondies des "desactivations" des entités et voir l'impact que cela a sur les autres ecrans. 
Par exemple, pour le cas cites par Fred:
    "lorsqu'on désactive un locataire celui ci ne devrait plus non plus apparaitre dans la dropdown "locataire" de l'ecran  
    "Creation d'une location"."
Pour moi ca doit être le contraire : la dropdown dans l'ecran de creation des locations doit afficher les locataires non-actifs, les autres etant assignes deja a une location

**Comment by krieklambic** [comment]
Ouh là, c'est encore plus poussé ca ! :-)

En fait le status "inactif" tel que l'Aiglon l'entend est une sorte de delete logique. Ce sont des gens qui ne font plus de business avec eux et qu'ils veulent voir disparaitre de leur liste.

L'inactif comme tu l'expose la veut plutot dire "Un locataire qui est déjà engagé dans une location ne doit plus etre proposé lors de la creation d'une nouvelle location"... 
A disuter aussi parce que, par exemple, un parent pourrait louer plusieurs kots pour tous ses enfants.
Ou bien, tu pourrais louer une maison toi y vivre et un appartement pour ta maitresse.

**Comment by bhosselet** [comment]
Attention les amis ... ca part en vrille ....  Vous n'avez rien écouté de ce que j'ai raconté la semaine dernière ou quoi?
Pour rappel ... je me suis engagé vis-à-vis de l'agence a gérer un statut actif/inactif sans aucune logique, automatisme ou validation.  On gère juste l'affichage, via un check-box comme résumé ci-dessus.  Je suis d'accord avec vous que ce serait bien d'avoir une analyse poussée afin d'étendre la fonctionnalité, mais c'est tout à fait "out of scope" pour l'instant.  Nous n'avons ni le temps d'analyser, encore moins d'implémenter, et financièrement l'agence ne paiera pas ce genre de supplément.  En résumé, on se base sur le résumé de Benoit pour l'implémentation, le reste on verra plus tard.  En terme d'affichage, il faut evidemment qu'un objet désactivé n'apparaisse plus dans les drop-down, mais pour le reste c'est a l'utilisateur de garantir l'integrite de ses donnees.

**Comment by krieklambic** [comment]
D'accord pour laisser tomber l'intégrité. Mais il n'empeche: Il faut analyser l'etat des lieux et dresser une liste exhaustive des liste, dropdowns (et autres conséquences) , sinon ca ne rime a rien...

**Comment by comexis** [comment]
Non j'ai rien ecoute chef, j'etais pas la... :)

**Comment by btytgat** [comment]
Visualisation du statut 
Dans les écrans «Liste des locataires» et «Détails d’un locataire», le statut actif ou non actif sera affiché après le champ «Nom».
Par défaut seuls les locataires actifs sont affichés.

Comment faire réapparaître les locataires désactivés
Pour voir réapparaître, dans la liste des locataires, ceux qui sont en statut non actif, l’utilisateur pourra cliquer sur un nouveau bouton en haut de la liste, à droite du filtre déjà existant.
Ce bouton , non coché par défaut, sera intitulé par exemple «Afficher aussi les Non actifs».
Attention, ces locataires restent désactivés.

Ce qui est implémenté est l'inverse de ce qui est décrit.
L'idée était d'afficher par défaut uniquement les actifs (logique puisque le but est d'alléger les listes) et de voir les inactifs par une action utilisateur (cliquer sur un bouton, cocher une case, ...)
Juju, gros boulot pour changer ?

**Comment by comexis** [comment]
Tant que fred n'a pas comitte ses changements dans github, je ne saurais pas repondre avec certitude a cette question. 
Mais à première vue cela devrait etre modifiable sans grand changement

**Comment by krieklambic** [comment]
Oh ben faudra juste ajouter un event "click" sur la checkbox a l initialisation...

---

**Comment by comexis** [comment]
J'ai corrige les derniers petits bugs, ca devrait fonctionner maintenant. 

J'ai activer le tri filtre actif/non actif  sur les locataires et proprietaires. On peut l'activer facilement pour les autres entites.

Benoit T, lorsque tes tests sont OK pour toi, tu peux fermer l'issue.

Julien

**Comment by btytgat** [comment]
Tous les locataires sont inactifs quand j'ouvre Napoléon.
Clic sur "mes locataires" ---> liste vide ok puisque "Montrer uniquement les éléments actifs" est coché.
Je décoche ---> toute la liste apparaît : ok puisque tous inactifs.
J'édite le premier (BECKER), l'active, le sauve puis retour liste.
BECKER apparait actif : ok mais "Montrer uniquement les éléments actifs" est décoché.
Je coche : BRUYERE reste là actif : logique
Je décoche : J'ai bien tous mes inactifs mais BECKER actif est toujours là.

**Comment by btytgat** [comment]
Tous les locataires sont inactifs quand j'ouvre Napoléon.
Clic sur "mes locataires" ---> liste vide ok puisque "Montrer uniquement les éléments actifs" est coché.
Je décoche ---> toute la liste apparaît : ok puisque tous inactifs.
J'édite le premier (BECKER), l'active, le sauve puis retour liste.
BECKER apparait actif : ok mais "Montrer uniquement les éléments actifs" est décoché.
Je coche : BRUYERE reste là actif : logique
Je décoche : J'ai bien tous mes inactifs mais BECKER actif est toujours là.

**Comment by comexis** [comment]
Corrigé et monté en test

**Comment by btytgat** [comment]
E perfecto.
