### ISSUE TITLE
Détail locataire - adresse de location

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#107]
Détails locataire
BECKER
Rue Neuve

OK

Retour liste

SCHAACK
adresse de location : Rue Neuve = faux
F5, OK

**Comment by pfdz** [comment]
D'après l'explication des symptômes, je pense avoir identifié le problème, voici mon analyse :

Lors de la création d'un nouveau locataire, le détail affiche une adresse de location (?) qui correspond au dernier bien que j'ai créé la veille, puis j'ai cliqué sur d'autres biens et j'ai constaté qu'en revenant sur le détail du nouveau locataire, l'adresse de location avait changé en une autre que je n'ai pas créée. En faisant, F5, l'adresse de location a disparu. Mais en continuant la navigation et en retournant sur le nouveau locataire (ce n'est apparemment pas systématique) une adresse de location réapparaît. J'ai constaté ensuite que l'adresse de location correspondait au dernier locataire que j'ai consulté ayant une adresse de location dans la liste des locataires.

**Comment by comexis** [comment]
corrigé et monté en test
