### ISSUE TITLE
Statut actif/non actif sur les propriétaires.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#108]
Tous les propriétaires sont inactifs quand j'ouvre Napoléon.
Clic sur "mes propriétaires" ---> liste vide ok puisque "Montrer uniquement les éléments actifs" est coché.
Je décoche ---> toute la liste apparaît : ok puisque tous inactifs.
J'édite le premier (BRUYERE), l'active, le sauve puis retour liste.
BRUYERE apparait actif : ok mais ""Montrer uniquement les éléments actifs" est décoché.
Je coche : BRUYERE reste là actif : logique
Je décoche : J'ai bien tous mes inactifs mais BRUYERE actif est toujours là.

Julien tu peux jeter un oeil svp quand tu as le temps ?
J'ai essayé de décrire de façon précise mais reste à disposition.
Merci,
Benoît T.

**Comment by comexis** [comment]
je ferme cette issue car on c'est relatif a l'issue 106 et c'est corrigé
