### ISSUE TITLE
GWTChosen : information (non)affichée

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#112]
V. ZOHO : DRAMAIXJ20120925

**Comment by pfdz** [comment]
Pour une meilleure lisibilité du problème posé ( liste déroulante - GWT Chosen), je fais un petit récapitulatif des documents déposés sur Zoho par Benoit T. ainsi que ma propre analyse :

< Test de Benoit T >
- Lors de l'édition d'un bien immobilier, le propriétaire actuel et
  actif n'apparait pas comme choix par défaut de la liste déroulante.
  (DRAMAIXJ20120831)

REPARE / issue 109 closé (bty) ok pour moi
- Lors de l'édition d'un bien immobilier, on effectue un changement de
  propriétaire. Si on créé un nouveau bien immobilier, la liste déroulante
  affiche par défaut, le dernier propriétaire issu de la précédente
  modification. (DRAMAIXJ20120903)

REPARE / issue 110 closé (bty) ok pour moi

---
- Lors de l'édition d'un bien immobilier, le comportement de la liste
  déroulante est hétérogène. Par exemple, dans le cas de l'édition d'un
  bien du propriétaire Van Olffen , la liste déroulante affiche Van Olffen
  après une actualisation de la page. Néanmoins, dans un second essai, la
  liste déroulante n'affiche pas l'ancien propriétaire et ce, même après
  l'actualisation de la page. (DRAMAIXJ20120925)

NON REPARE / issue 112 créé (bty) encore à faire pour moi

---

< Test de Paul F. >
- L'édition d'un bien immobilier me donne à 90 %  le même
  comportement et ce quelque soit la source (auteurs) des jeux d'essai
  propriétaire, bien et locataire. A savoir, que la liste déroulante ne
  m'affiche pas l'ancien propriétaire même après l'actualisation de la
  page (F5 + ctrl F5). Cependant, j'ai noté que lors d'une actualisation
  ou d'un accès direct par le lien, le nom de l'ancien propriétaire
  s'affiche succinctement avant de disparaitre. Les 10% restant me donnent
  le comportement souhaité, c'est-à-dire l'affichage du propriétaire par
  défaut dans la liste déroulante (avec ou sans actualisation de la page).

**Comment by comexis** [comment]
Corrige et monte en test
