### ISSUE TITLE
Minor - Liste propriétaire - sélection

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#17]
Quand on revient sur la liste depuis l'ecran de détail, il faudrait que l'élement dont on a affiché le détail ne soit plus sélectionné. De cette façon on peut directement parcourir la liste à la recherche d'un autre élément avec l'aide des flêches monter/descendre.

**Comment by comexis** [comment]
L'element n'est maintenant plus selectionne quand on revient sur la table
Par contre j'ai tjs un probleme de focus
