### ISSUE TITLE
Minor - Edition propriétaire/locataire - Permettre de changer l'année dans le calendrier

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#19]
Si je veux remplir le champ "date de naissance" d'un propriétaire  p.ex., né en 1960 , je dois reculer d'un mois à la fois (calendar). Il devrait avoir la possibilite de changer l'année directement

**Comment by bhosselet** [comment]
Benoit,

Peux-tu fournir plus d'infos ... pas évident à comprendre ...

MErci

Benoit

**Comment by comexis** [comment]
j'ai modifié l'issue en fonction du mail envoyé par benoit T.

**Comment by btytgat** [comment]
Commentaire du client : - LOCATAIRES 
Date de naissance locataire le tableau ne sert à rien car il
nous amène en 2012

**Comment by comexis** [comment]
J'ai modifie le widget pour permettre de changer l'annee.

Pousse en test.

Bennoit T peux tu checker si c'est bon comme ca ?
