### ISSUE TITLE
Minor - Any lists - tri

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#22]
Listes : A>Z … Z>A

**Comment by comexis** [comment]
Fixer via le commit 63c11107bdf3b1fad54c1019ec02c09967f7914e

**Comment by btytgat** [comment]
Propriétaire : liste de A > Z mais locataire liste de Z > A

**Comment by btytgat** [comment]
Commentaires du client : Classement par ordre alphabétique des
propriétaires ; - LOCATAIRES : Classement par ordre alphabétique ; - BIENS: Classement par ordre alpha des proprios
J'ai passé un coup de fil à l'agence pour expliquer que cliquer sur l'en-tête de colonne classait de A>Z ou de Z>A.
