### ISSUE TITLE
Minor - Les suggestions des profession et nationalites doivent venir du serveur

### ISSUE THREAD

**Issue by comexis** [comexis/napoleon#3]
Tout comme les pays, ville et code postaux, on doit proposer la liste de profession et nationalites qui ont deja ete rentre dans le systeme. Pour le moment ces listes sont hardcodees. Il faut implementer un appel vers le serveur afin de ramener ces listes

**Comment by xplatiau** [comment]
C'est fait mais il reste un problem de rafraichisement de ces listes
