### ISSUE TITLE
Minor - Edition propriétaire - Warning

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#30]
(5 <= honoraires <= 15) faux ---> warning.
Ce warning n'est pas complet : Le champ honoraires doit être inférieur à 15 .
Je propose "Le champ "honoraires" doit être compris entre 5 et 15 % inclus."

**Comment by xplatiau** [comment]
Refuse ce qui n'est pas numeric et positif. Refuse les % hors interval [5-15]
