### ISSUE TITLE
Minor - Biens - Nouveau bien - combos

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#31]
A la création d'un nouveau bien, les 3 combos (type de bien, état, propriétaire) sont remplis.
Y-a-t-il un moyen de créer une option " " sélectée au départ par défaut pour ces 3 combos ?

**Comment by comexis** [comment]
Oui !
XAvier,

Il suffit de rajouter une valeur a chaque enum (NONE) et de selectionner celle ci par defaut (voir la nouvelle signature de la methode selectTextItemBoxByValue de l'objet UiHelper)
