### ISSUE TITLE
Major - Edition locataire - zones manquantes

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#32]
Dans StatutZonesEcranscompte.doc, le client a prévu 2 adresses : domiciliation et location.
Dans l'écran 1 seule apparaît.
Dans StatutZonesEcranscompte.doc, le client a prévu et insisté sur la référence.
(il veut savoir actuellement locataire LOXHET = blancschevaux 36/1)
Cette zone référence n'est pas là.

**Comment by xplatiau** [comment]
Sera fixé quand on mettra en place les locations.

**Comment by comexis** [comment]
Xavier, c'est fixé ? Si oui close le bazard
