### ISSUE TITLE
Major - Edition propriétaire - validation

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#34]
J'ai créé :
nom : 007
prénom : OSS117
honoraires : 7
mail : girls007@cinema.eu

Ne faudrait-il pas, au moins sur la zone mandatory définie par le client (nom) renforcer la vadidation ?

Idem (sauf honoraires) pour le locataire.

**Comment by comexis** [comment]
Qu'est ce que tu entends renforcer la validation ??

**Comment by xplatiau** [comment]
J'ai ajouté le contrôle suivant: ^[\p{L}\p{M}' .-]+$

**Comment by xplatiau** [comment]
Ca ne marche plus. J'ai viré le RE. Faut que je charche pourquoi

**Comment by comexis** [comment]
pour moi faut pas se casser la tete sur le validation du nom... On peut accepter tout les caracteres

**Comment by btytgat** [comment]
Accord passé avec Julien le 21/02 : pour cette version 1, on tient compte des mandatory voulus par le client (liste officielle sur github). Les différentes validations viendront pour une version ultérieure.
