### ISSUE TITLE
Minor - Il manque le code postal dans l'affichage de l'addresse des owners et tenants

### ISSUE THREAD

**Issue by comexis** [comexis/napoleon#38]
Depuis que l'on a scinde le code postal de la ville, celui ci n'est plus affiche dans les ecrans de details du proprio et du locataire

**Comment by xplatiau** [comment]
Maintenant affichage multiligne de tout

**Comment by btytgat** [comment]
Pas de CP pour les tenants.

**Comment by btytgat** [comment]
Reopened par erreur, sorry. Confusion liste et consultation.
