### ISSUE TITLE
Liste officielle (from client) : Mandatory (M) - Facultative (F)

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#39]
PROPRIETAIRE
LIBELLE 
Statut     F  
Civilité     F 
Prénom     F  
Nom     M  
Honoraires     F  
Iban     F  
Bic     F  
Adresse     F  
code postal     F  
Localité     F  
Pays     F  
Téléphone     F  
Gsm     F  
Fax     F  
Mail     F  
date de naissance     F
lieu de naissance     F
Nationalité     F  
Profession     F  
registre national     F
Marié     F  
régime matrimonial     F

LOCATAIRE
Civilité     F  
Prénom     F  
Nom     M  
type de locataire     F  
adresse de domiciliation     F  
code postal     F
Localité     F  
Pays     F  
adresse de location     M  
Référence     M  
Téléphone     F  
Gsm     F  
Fax     F  
Mail     F  
Iban     F  
Bic     F  
date de naissance     F  
lieu de naissance     F  
Nationalité     F  
Profession     F  
registre national     F 
Marié     F  
régime matrimonial     F

BIEN
Référence     M  
Copropriété     F 
Syndic     F  
Adresse     F  
Téléphone     F  
Gsm     F  
Mail     F  
adresse du bien     M  
n°     M  
Bte     M  
code postal     M  
Localité     M  
Quartier     F  
type de bien     F  
Etat     F  
Superficie     F  
Propriétaire     M  
Téléphone     F  
Gsm     F  
Mail     F

**Comment by xplatiau** [comment]
Devrait être fixé maintenant.
