### ISSUE TITLE
Harmoniser la presentation des adresses

### ISSUE THREAD

**Issue by bhosselet** [comexis/napoleon#40]
Séparer le numéro de la rue dans les objets "proprietaire" et "locataire", comme c'est le cas pour l'objet "bien", et harmoniser la présentation sur tous les écrans.

**Comment by xplatiau** [comment]
Est-il nécessaire de séparer le n° de la rue ?

**Comment by bhosselet** [comment]
Oui, c'est plus propre, et plus coherent par rapport aux biens.
Mais si cela met notre release en danger, on peut faire cela plus tard.

Benoit

-----Original Message-----
From: xplatiau
[mailto:reply+i-3313225-af14e3a9004d742eeb48e875fc287904823b8a94-1442621@rep
ly.github.com] 
Sent: mardi 21 février 2012 18:49
To: bhosselet
Subject: Re: [napoleon] Harmoniser la presentation des adresses (#40)

Est-il nécessaire de séparer le n° de la rue ?

---

**Comment by xplatiau** [comment]
J'ai ajouté le n° dans les proprio et locataire (comme les biens)
