### ISSUE TITLE
Minor - bien

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#43]
Le standard d'adressage de propriétaire et locataire :

Adresse : Rue de la Bascule, 11
Pays : Belgique
CP : 7000
Ville : Mons

n'est pas le même dans bien : adressage du syndic et adressage du bien

J'envoie ce matin au client (et je lui resonne) une liste sur un design (MAJUSCULE, minuscule, Mabc, format tél, adresse, ...) pour que tout le monde soit d'accord sur un standard commun.

**Comment by xplatiau** [comment]
J'ai changé comme dans proprio et locataire. Faudrait formater correctement tout ca (Julien?)
