### ISSUE TITLE
Severe - Listes LUMZY vs listes NAPOLEON

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#45]
Propriétaire : OK

Locataire : Adresse (titre NAPOLEON) <> Adresse de domiciliation (titre LUMZY)

Bien : A ajouter, colonne Propriétaire, colonne Code postal

**Comment by xplatiau** [comment]
Faudrait changer l'adresse de domiciliation (Julien ?). Sinon j'ai ajouté les colonnes dans Bien. Question: c'est bien le n° GSM et Tel du proprio qu'il faut monter ?

**Comment by btytgat** [comment]
Question: c'est bien le n° GSM et Tel du proprio qu'il faut monter ? YES
