### ISSUE TITLE
Création d'une location

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#66]
Champ type de location non refreshé (dans mon test = "résidence principale" = type de la création précédente)
Il serait mieux que le refresh nous donne la valeur "-" (càd inconnu) par défaut.

**Comment by krieklambic** [comment]
Il faudra uniformiser un peu le contenu des dropdown....
Dans certain cas la valeur de l'element "-" est "-", dans d'autre cas c'est "NONE"....

De plus tout devrait etre defini dans des constantes et non a chaque ligne de code
