### ISSUE TITLE
Minor - Création d'une location.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#71]
J'ai créé un nouveau locataire (toto)
J'ai créé une nouvelle location mais le combo "locataire" n'est pas refreshé (toto n'est pas dans la liste)
Refresh manual obligatoire pour imputer cette location au nouveau locataire.

**Comment by xplatiau** [comment]
Julien peux-tu y regarder ? Le probleme est général dans l'appli.

**Comment by comexis** [comment]
C'est corrige ca maintenant non ?

**Comment by btytgat** [comment]
yes.
