### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#79]
Liste des dépenses/Liste des payements
Le lien "parent" : NEUVE32/0 Rue Neuve, 32 4970 STAVELOT ne marche pas.

**Comment by krieklambic** [comment]
Les hyperliens marchent enfin (et sont affichés en bleu pour qu'ils soient plus visible.
J'ai aussi corrigé certains boutons qui ne marchaient pas (renvoyaient au dashboard).

Il faudrait maintenant retester tous les liens/boutons voir s'il y a encore eventuellement des erreurs
