### ISSUE TITLE
Minor - date de fin pour le premier payement locataire

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#80]
Location du 10/01/2015 au 31/03/2015

Le système propose

10/01/2015 - 09/02/2015
10/02/2015 - 28/02/2015
01/03/2015 - 31/03/2015

Il faudrait

10/01/2015 - 31/01/2015
etc

La personne qui encode le premier payement adaptera le loyer.

**Comment by comexis** [comment]
la date de fin pour tout payment est maintenant le dernier jour du mois
