### ISSUE TITLE
Minor - refresh du combo propriétaire.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#81]
Création d'un propriétaire puis immédiatement création d'un bien.
(C'est comme ça que l'aiglon travaille).
Le combo propriétaire n'est pas à jour.

**Comment by comexis** [comment]
impossible a reproduire et vu le code je dirais meme que c'est impossible que ca se passe

**Comment by btytgat** [comment]
3/4
Création d'un propriétaire puis immédiatement création d'un bien.
(C'est comme ça que l'aiglon travaille).
Le combo propriétaire n'est pas à jour.
en production promis je l'ai vu ça ne marchait pas

4/4
Création d'un propriétaire puis immédiatement création d'un bien.
(C'est comme ça que l'aiglon travaille).
Le combo propriétaire n'est pas à jour.
en test je viens d'essayer le proprio n'est pas là

**Comment by comexis** [comment]
ca devrait etre bon maintenant
