### ISSUE TITLE
Minor - retour info serveur > client.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#82]
Après le save d'un nouveau locataire/d'une nouvelle location, on devrait avoir l'écran avec les données sauvées.
Mais on obtient : "chargement des données ... attendre"
Et attendre ... on peut attendre.

**Comment by btytgat** [comment]
Menu locataire     clic
Mes locataires     clic
"LECLOUX" dans la liste      clic

> > > chargement des données veuillez attendre

essai de F5 mais pas de changement

**Comment by comexis** [comment]
Il manquait un index... ca devrait etre bon maintenant
