### ISSUE TITLE
Création d'un propriétaire = personne morale.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#84]
Quand le propriétaire est une personne morale, ajouter le champ TVA.
(V. écran LUMZY "propriétaire")

**Comment by krieklambic** [comment]
Champ ajouté.
Pour le moment il est visible dans tous les cas. 

On pourrait le cacher/disabler si c'est une personne morale. Mais alors, il serait nécessaire de définir précisément quels sont les critères qui font qu'un Propriétaire est une personne morale.
