### ISSUE TITLE
Garantie locative d'une location.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#85]
Actuellement, la garantie locative peut être versée
     1) en cash
     2) sur un compte bancaire (bloqué) = IBAN + BIC
Ajouter
     3)compte agence aiglon avec un "suggest"
(V. écran LUMZY)

**Comment by krieklambic** [comment]
Suggest marche comme les autres: Pour voir la nouvelle valeur, il faut se delogger/relogger...
