### ISSUE TITLE
Minor - création location

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#90]
1° fois : message chargement des données ... veuillez attendre
2° fois : retour sur mes biens, select du bien , gestion des locations, nouvelle location : OK

**Comment by btytgat** [comment]
Environnement de production/juste après la connection
Essai 1 :
Biens immobiliers     clic
Dans la liste GAUMAIS2/408     clic
Gestion des locations     clic
Nouvelle location     clic
Ecran Création d’une location : chargement des données … veuillez attendre
Tout de suite après, essai 2
Mes biens     clic
Dans la liste GAUMAIS2/408     clic
Gestion des locations     clic
Nouvelle location     clic
Création d’une location avec le bien GAUMAIS2/408 : OK

**Comment by comexis** [comment]
L'erreur existait ausse en test...
Corrigé et poussé sur l'environement test de google app engine
