### ISSUE TITLE
Major - Modif impossible pour une location.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#91]
Biens immobiliers     clic
Mes biens     clic
Choix d'un bien dans la liste     clic
Gestion location     clic
Choix d'une location dans la liste     clic
Editer     clic
Modification des charges (p.ex)     sauver     clic
Message "la référence comptable nnn est déjà utilisée pour l'année académique nnnn-nnnn" donc modification impossible

**Comment by comexis** [comment]
fixed and pushed on test
