### ISSUE TITLE
Paiement loyer : enlever le blocage nombre maximal de loyers perçus = nombre de mois de la location.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#97]
Paiement loyer : enlever le blocage nombre maximal de loyers perçus = nombre de mois de la location.

**Comment by krieklambic** [comment]
(Le blocage etait en fait sur la date de fin de la periode)

**Comment by btytgat** [comment]
Issue 97 : Un problème subiste

Le blocage a été enlevé, ce qui permet maintenant d’encoder plus de loyers qu’il n’y a de mensualités prévues.
Frederic a mis dans’ github’ que le blocage était en fait sur la date de fin de la période.

Test pour une location du 1/6 au 31/8 sur le bien ‘test nouvelle version’ :
-          Premier loyer perçu : le système donne par défaut les dates du 1/6 au 30/6
-          Deuxième loyer perçu : le système donne du 1/7 au 31/7 
-          Troisième loyer perçu (un demi-loyer : 50 euros) :  le système donne du 1/8 au 31/8 
-          Mais si j’encode un quatrième payement (50 euros : seconde moitié du loyer pour 8/2012) : le système me donne comme dates du 1/9 au 31/8 ! Et si on sauve en gardant ces dates-là : message d’erreur de validation : 
  « La date de sortie doit être postérieure à la date d’entrée »
-          è l’utilisateur peut bypasser cette validation en mettant comme dates ‘du 1/8 au 31/8, et sauver, MAIS : ce loyer n’apparait ensuite pas dans la liste.
-          Je me dis que le problème est peut-être causé par un double loyer du 1/8 au 31/8 : j’essaye encore avec un loyer de 25 euros pour la période du 3/8 au 31/8 
-          è Non, ce payement n’apparait pas non plus
  Conclusions : 
  1°) Le système continue de proposer pour chaque loyer, les dates de début et de fin de la mensualité, en fonction du nombre de payement. 
  Si l’utilisateur n’y fait pas attention et ne corrige pas ces dates, il risque de ne plus s’y retrouver : la date qui aura du sens sera finalement la date du payement. 

2°) Vérifier si les payements > le nombre de mensualités sont créés dans la DB d‘une part car ils ne sont pas repris dans la liste

3°) Si le point 2 ci-dessus est OK : résoudre alors le problème de l’affichage de ces payements dans la liste

**Comment by krieklambic** [comment]
Pour éviter des problemes en cascades, on a remis la limitation à 1 payement par mois de location. 

J'ai ajouter un champ commentaire dans les ecrans de paiement pour gérer les cas de paiements partiels.
