### ISSUE TITLE
 Tri des colonnes : chaque colonne doit être triée par défaut.

### ISSUE THREAD

**Issue by btytgat** [comexis/napoleon#99]
Tri des colonnes : chaque colonne doit être triée par défaut. De plus, lors d'un retour à une liste, le tri initial et la pagination doivent être récupérés.

**Comment by btytgat** [comment]
Chaque colonne doit être triée par défaut lors de l’affichage des listes.
Liste des propriétaires :
-    tri alphabétique sur le nom (l’agence y ajoutera un début de prénom en cas de doublons…)

Liste des locataires :
-    tri alphabétique sur le nom (l’agence y ajoutera un début de prénom en cas de doublons…)

Liste des biens :
-   tri sur     1°) la date de disponibilité du bien (voir point 4.1 ci-dessus) : les biens libres d’abord
  2°) la référence du bien (alphabétique)

**Comment by krieklambic** [comment]
Juju, je te laisse regler les problemes de sort.

J'ai beau appeler table.getColumnSortList().push(...), la petite fleche se met bien au dessus de la colonne, mais les données ne sont pas triées...

**Comment by comexis** [comment]
ok je vais regader a ca

**Comment by comexis** [comment]
Fred, pour info, les CellTable font tjs l'hypothese que les données arrivent triées. 
table.getColumnSortList().push(...) permet juste de refléter au niveau des headers de la table le tri par défault des données.

Il faut donc simplement trier la liste niveau serveur (ou client juste au moment ou on reçoit les donnes, mais c'est mieux du cote serveur).

**Comment by comexis** [comment]
Liste des propriétaires : tri alphabétique sur le nom 
Liste des locataires : tri alphabétique sur le nom
Liste des biens : tri sur la référence du bien (alphabétique)
